using System;
using System.IO;
using System.Text;

void foo()
{
    throw new Exception("foo");
}

void main()
{
    try
    {
        foo();
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine(ex.ToString());
    }
}